# syntax=docker/dockerfile:1

## Build
FROM golang:1.19

RUN mkdir /app
ADD . /app
WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY *.go ./

RUN go build -o /echoapp

EXPOSE 1323


CMD [ "/echoapp" ] 